### ISSUE TITLE
BUG: encountered invalid symbol

### ISSUE THREAD

**Issue by Gary-oak-Star** [ekiwi/patron#1]
Hi, I noticed that this repo may be the first implementation to use bitwuzla to solve btor in BMC. However, I encountered a bug when I tried using it (rename this to btor2 is needed).
[ponylink-slaveTXlen-sat.txt](https://github.com/ekiwi/patron/files/13692299/ponylink-slaveTXlen-sat.txt)

When solving this btor2, it showed `encountered invalid symbol`, I attached some part of screenshot here, and the complete log has been attached as well

[log.txt](https://github.com/ekiwi/patron/files/13692310/log.txt)

<img width="1616" alt="image" src="https://github.com/ekiwi/patron/assets/120406793/491c1bab-23b0-4e46-a7d1-1dc36da6d958">

**Comment by ekiwi** [comment]
Thanks for reporting this. Unfortunately this repository is still undergoing big changes and I am pretty busy until later next year. If you find a fix, feel free to PR, but I won't be able to investigate myself.

**Comment by ekiwi** [comment]
There is a good chance this is now fixed with: https://github.com/ekiwi/patron/commit/891791bb58d49a3d0d13d65a022fb6c53102274d
